# Generated by Django 4.2.7 on 2025-10-20 19:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('creations', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='creation',
            name='category',
            field=models.CharField(choices=[('bois', 'Création Bois'), ('3d', 'Impression 3D'), ('mixte', 'Mixte Bois/3D'), ('gravure', 'Gravure')], max_length=10, verbose_name='Catégorie'),
        ),
    ]
